// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASJhBxMM8ao5U1ng35ClyEQiaFZZKdeOk',
    appId: '1:193195765513:web:b9da65006684eb0f28edd8',
    messagingSenderId: '193195765513',
    projectId: 'pollafutbolera-9c9c5',
    authDomain: 'pollafutbolera-9c9c5.firebaseapp.com',
    storageBucket: 'pollafutbolera-9c9c5.appspot.com',
    measurementId: 'G-3Q0M41ST00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ObB_n1wFYZa8T2CKHFYVraZacMErVww',
    appId: '1:193195765513:android:c98ff8f537e50bcf28edd8',
    messagingSenderId: '193195765513',
    projectId: 'pollafutbolera-9c9c5',
    storageBucket: 'pollafutbolera-9c9c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvkNr_JyBMm_9U-XaQDi39L9ouRuXdFkE',
    appId: '1:193195765513:ios:82c382bc7a96ea0c28edd8',
    messagingSenderId: '193195765513',
    projectId: 'pollafutbolera-9c9c5',
    storageBucket: 'pollafutbolera-9c9c5.appspot.com',
    iosClientId: '193195765513-ehnqcd9jdet9s808qkgfiad0p4olbgrs.apps.googleusercontent.com',
    iosBundleId: 'co.devpaul.pollaFutbolera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvkNr_JyBMm_9U-XaQDi39L9ouRuXdFkE',
    appId: '1:193195765513:ios:82c382bc7a96ea0c28edd8',
    messagingSenderId: '193195765513',
    projectId: 'pollafutbolera-9c9c5',
    storageBucket: 'pollafutbolera-9c9c5.appspot.com',
    iosClientId: '193195765513-ehnqcd9jdet9s808qkgfiad0p4olbgrs.apps.googleusercontent.com',
    iosBundleId: 'co.devpaul.pollaFutbolera',
  );
}
